---
- name: Testing andrewrothstein.sops
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'sops --version'
      ansible.builtin.command: sops --version
      changed_when: false
      register: sops_test_output
    - name: Output from 'sops --version'
      ansible.builtin.debug:
        msg: '{{ sops_test_output.stdout }}'
