---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/sops --version
      register: sops_test_output
    - name: sops --version
      debug:
        msg: '{{ sops_test_output.stdout }}'
