---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ sops_url }} to {{ sops_installed_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ sops_url }}'
    dest: '{{ sops_installed_exe }}'
    checksum: '{{ sops_checksum }}'
    mode: 0755
- name: linking {{ sops_link }} to {{ sops_installed_exe }}
  become: true
  become_user: root
  file:
    src: '{{ sops_installed_exe }}'
    dest: '{{ sops_link }}'
    state: link
